[build]
  command   = "pnpm install --frozen-lockfile && pnpm run build"
  publish   = "apps/web/dist"
  # Point functions to the TypeScript sources; Netlify will transpile/bundle
  functions = "apps/api/src"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_PNPM = "true"

# functions proxy (if you use them)
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# SPA routing
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
