[build]
  command   = "pnpm install --frozen-lockfile && pnpm run build"
  publish   = "apps/web/dist"
  functions = "apps/api/dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_PNPM = "true"

# SPA routing for React Router
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Cache static assets (optional)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
